### ISSUE TITLE
Using an "await barrier" at the end of a script causes the test to hang

### ISSUE THREAD

**Issue by AdrianCozma** [k3po/k3po#237] opened 2015-10-16 14:40 UTC
I am trying to use a barrier at the end of a robot script in order to make sure that the session opened by that script is not closed and this is causing the test to timeout.
I tried to use this in a script used for testing "kill all session by principal"; please see the logs for the test results
I'm not sure if this is a bug or if I'm using the barrier in a way it was not intended to be used.

[k3po_log.txt | uploaded via ZenHub](https://files.zenhub.io/56210a4257ce93c165dd6b16)

[script.txt | uploaded via ZenHub](https://files.zenhub.io/56210a4257ce93c165dd6b15)

[log.txt | uploaded via ZenHub](https://files.zenhub.io/56210a4257ce93c165dd6b17)

**Comment by AdrianCozma** [comment] 2015-10-20 15:46
one workaround that worked for my test was to add a `write "something"` after the barrier(the script stopped hanging after adding it)
[test_passes_with_this_script.txt | uploaded via ZenHub](https://files.zenhub.io/56266187e65f59e62e8b3770)

**Comment by cmebarrow** [comment] 2015-11-13 00:17
Your test script that is failing ends with write await. That is incorrect because the intention of that is to delay any subsequent writes (or other downstream commands like close) in the script, so it makes no sense if it is the last instruction in the script. You can achive what you want using a script like the following: 
```
accept tcp://localhost:7000
accepted
connected

read "HELLO"

closed

connect tcp://localhost:7000
connected

write "HELLO"

write await CLOSE_REQUESTED
close
closed
```

**Comment by cmebarrow** [comment] 2015-11-13 00:19
@AdrianCozma For the reasons explained above I am closing this as not a bug. Feel free to reopen if you disagree.

**Closed by cmebarrow** 2015-11-13 00:19 UTC
Labels: bug

**Comment by cmebarrow** [comment] 2016-11-08 17:20
Note: I have filed https://github.com/k3po/k3po/issues/379 for a similar issue
