### ISSUE TITLE
add support for deferred accept/connect

### ISSUE THREAD

**Issue by pkhanal** [k3po/k3po#103] opened 2015-01-14 18:07 UTC
In some cases, accept/connect url are only resolved as a payload of a stream. There is no way we can trigger accept/connect after the accept/connect url is resolved from a stream.
We need some kind of **wait/notify** on accept/connect.

See #104 for example script.

**Comment by jfallows** [comment] 2015-01-27 06:58
@pkhanal this appears to be a duplicate of #29, agree?

**Comment by pkhanal** [comment] 2015-01-27 07:14
@jfallows , yes this issue is the duplicate of #29

**Comment by jfallows** [comment] 2015-01-27 07:15
Okay, thanks @pkhanal - closing as duplicate.

**Closed by jfallows** 2015-01-27 07:15 UTC
Labels: enhancement
