### ISSUE TITLE
HttpRobotBehaviorIT#shouldAcceptWebsocketHandshake failing Test Timed out with a NPE in LocationInfo

### ISSUE THREAD

**Issue by dpwspoon** [k3po/k3po#55] opened 2014-10-20 17:49 UTC
#### Reproduce sporadically by running 

```
until ! mvn integration-test -Dit.test=HttpRobotBehaviorIT#shouldAcceptWebsocketHandshake -X; do echo "trying again"; done
```

#### target/failsafe-reports/org.kaazing.robot.driver.http.HttpRobotBehaviorIT.txt 
```
-------------------------------------------------------------------------------
Test set: org.kaazing.robot.driver.http.HttpRobotBehaviorIT
-------------------------------------------------------------------------------
Tests run: 17, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.812 sec <<< FAILURE! - in org.kaazing.robot.driver.http.HttpRobotBehaviorIT
shouldAcceptWebsocketHandshake(org.kaazing.robot.driver.http.HttpRobotBehaviorIT)  Time elapsed: 2.01 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 2 seconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:503)
	at org.jboss.netty.channel.DefaultChannelFuture.await(DefaultChannelFuture.java:234)
	at org.kaazing.robot.driver.http.HttpRobotBehaviorIT.shouldAcceptWebsocketHandshake(HttpRobotBehaviorIT.java:214)

```

####  Stack trace by turning logging all the way up:         Logger.getGlobal().setLevel(Level.ALL);
```
WARNING: An exception was thrown by ChannelFutureListener.
java.lang.NullPointerException
	at org.kaazing.robot.lang.LocationInfo.equals(LocationInfo.java:47)
	at org.kaazing.robot.lang.LocationInfo.compareTo(LocationInfo.java:56)
	at org.kaazing.robot.lang.LocationInfo.compareTo(LocationInfo.java:22)
	at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:290)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:157)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:146)
	at java.util.Arrays.sort(Arrays.java:472)
	at java.util.Collections.sort(Collections.java:155)
	at org.kaazing.robot.driver.behavior.visitor.GatherStreamsLocationVisitor$State.<init>(GatherStreamsLocationVisitor.java:100)
	at org.kaazing.robot.driver.Robot$3.operationComplete(Robot.java:295)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:413)
	at org.jboss.netty.channel.DefaultChannelFuture.setSuccess(DefaultChannelFuture.java:362)
	at org.kaazing.robot.driver.netty.channel.CompositeChannelFuture$NotifyingListener.operationComplete(CompositeChannelFuture.java:207)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
	at org.jboss.netty.channel.DefaultChannelFuture.setSuccess(DefaultChannelFuture.java:362)
	at org.kaazing.robot.driver.netty.channel.ChannelFutureListeners$ChannelFutureListenerDecorator.operationComplete(ChannelFutureListeners.java:51)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
	at org.jboss.netty.channel.DefaultChannelFuture.setSuccess(DefaultChannelFuture.java:362)
	at org.kaazing.robot.driver.netty.channel.CompositeChannelFuture$NotifyingListener.operationComplete(CompositeChannelFuture.java:207)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
	at org.jboss.netty.channel.DefaultChannelFuture.setSuccess(DefaultChannelFuture.java:362)
	at org.kaazing.robot.driver.behavior.handler.event.ReadHandler.messageReceived(ReadHandler.java:118)
	at org.kaazing.robot.driver.behavior.handler.event.ReadHandler.messageReceived(ReadHandler.java:63)
	at org.kaazing.robot.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:40)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:45)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:187)
	at org.kaazing.robot.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:107)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:40)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:45)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:187)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:40)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:45)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:187)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:40)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:45)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:187)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:97)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:97)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:97)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:97)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:97)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:97)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:97)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:40)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:45)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:187)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:40)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:45)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:187)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:40)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:45)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:187)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:40)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:45)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:187)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:40)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:45)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:187)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:40)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:45)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:187)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:40)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:45)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:187)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:40)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream0(SimplePrepareUpstreamHandler.java:45)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream1(ExecutionHandler.java:187)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:97)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:97)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.behavior.handler.event.AbstractEventHandler.handleUpstream1(AbstractEventHandler.java:97)
	at org.kaazing.robot.driver.behavior.handler.ExecutionHandler.handleUpstream0(ExecutionHandler.java:183)
	at org.kaazing.robot.driver.behavior.handler.prepare.SimplePrepareUpstreamHandler.handleUpstream(SimplePrepareUpstreamHandler.java:35)
	at org.kaazing.robot.driver.behavior.handler.LogLastEventHandler.handleUpstream(LogLastEventHandler.java:69)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

```

**Comment by jfallows** [comment] 2015-01-27 06:32
Can no longer reproduce due to refactored codebase, closing...

**Closed by jfallows** 2015-01-27 06:32 UTC
Labels: bug, wontfix
